name: Backend Tests

on:
  push:
    branches:
      - desenvolvimento
  pull_request:
    branches:
      - desenvolvimento

jobs:
  run-tests:
    name: Run Django Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências do backend
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes do Django
        working-directory: backend
        run: |
          python manage.py test